<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Authors>Piotr Falkowski</Authors>
    <Description>Serialize and deserialize easily from and to CSV.</Description>
    <Copyright>Piotr Falkowski © 2026</Copyright>
    <PackageProjectUrl>https://github.com/PFalkowski/Extensions.Serialization.Csv</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/PFalkowski/Extensions.Serialization.Csv</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>serialization,netcore,csv,extension-methods</PackageTags>
    <Version>2.2.0</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="19.0.0" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
